@startuml

abstract class Scheduler

Scheduler <|-- ComputationScheduler
Scheduler <|-- IoScheduler
Scheduler <|-- SingleScheduler
Scheduler <|-- TrampolineScheduler
Scheduler <|-- NewThreadScheduler
Scheduler <|-- ExecutorScheduler
Scheduler <|-- TestScheduler

hide members
@enduml