@startuml
interface ObservableSource
abstract class Observable

ObservableSource <|.. Observable

abstract class Subject
abstract class ConnectableObservable
class ObservableFilter
class ObservableMap
class ObservableLift

Observable <|-- Subject
Observable <|-- ConnectableObservable
Observable <|-- ObservableFilter
Observable <|-- ObservableMap
Observable <|-- ObservableLift

@enduml