@startuml

interface Observer<T>
interface MaybeObserver<T>
interface SingleObserver<T>
interface CompletableObserver
interface Disposable

class TestObserver<T>

Observer <|.. TestObserver
MaybeObserver <|.. TestObserver
SingleObserver <|.. TestObserver
CompletableObserver <|.. TestObserver
Disposable <|.. TestObserver


@enduml